### ISSUE TITLE
Missing dill

### ISSUE THREAD

**Issue by anderkve** [jeriek/xsec#4]
[A second issue that @jeriek and I discussed via email. Just registering it here to log it properly. Jeriek has a fix ready.]

For Python3 there is an indirect dependency on the `dill` module, related to unpickling the trained GPs. Here's how to reproduce it from a clean Python3 environment:
```
python3 -m venv myenv3/xsec_test
source myenv3/xsec_test/bin/activate
pip install xsec==1.0.0
xsec-download-gprocs -t gg
xsec-test ./gprocs
```
This gives the following error:
```
    Traceback (most recent call last):
      File "/home/anders/myenv3/xsec_test/bin/xsec-test", line 44, in <module>
        xsec.load_processes(processes)
      File "/home/anders/myenv3/xsec_test/lib/python3.8/site-packages/xsec/gploader.py", line 390, in load_processes
        PROCESS_DICT[process_xstype] = load_single_process(
      File "/home/anders/myenv3/xsec_test/lib/python3.8/site-packages/xsec/gploader.py", line 324, in load_single_process
        gp_reco = reconstruct_gp(model_file)
      File "/home/anders/myenv3/xsec_test/lib/python3.8/site-packages/xsec/gploader.py", line 216, in reconstruct_gp
        gp_model = joblib.load(file_object)
      File "/home/anders/myenv3/xsec_test/lib/python3.8/site-packages/joblib/numpy_pickle.py", line 575, in load
        obj = _unpickle(fobj)
      File "/home/anders/myenv3/xsec_test/lib/python3.8/site-packages/joblib/numpy_pickle.py", line 504, in _unpickle
        obj = unpickler.load()
      File "/usr/lib/python3.8/pickle.py", line 1210, in load
        dispatch[key[0]](self)
      File "/usr/lib/python3.8/pickle.py", line 1526, in load_global
        klass = self.find_class(module, name)
      File "/usr/lib/python3.8/pickle.py", line 1577, in find_class
        __import__(module, level=0)
    ModuleNotFoundError: No module named 'dill'
```

**Comment by jeriek** [comment]
Converting the Py2 joblib pickles (#2) to Py3 involved the `dill` library (see https://rebeccabilbro.github.io/convert-py2-pickles-to-py3/), so it appears that the new Py3 pickles depend on dill now for unpickling. Fixed in #5.
